name: ai-ml-90day
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - streamlit
      - fastapi
      - uvicorn
      - pytest
      - python-dotenv