name: Bug report
description: Create a report to help us improve
title: "[BUG] <short description>"
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1. Go to ... 2. Click ... 3. See error
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots