name: Feature request
description: Suggest an idea for this project
title: "[FEAT] <short description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
  - type: textarea
    id: extra
    attributes:
      label: Additional context